### ISSUE TITLE
Add compatibility information.

### ISSUE THREAD

**Issue by oknoorap** [NamPNQ/You-Dont-Need-Javascript#34] opened 2016-07-09 09:20 UTC
This repo is awesome, this could be replacing some basic js library (accordion, tab). But, please add browsers compatibility information. e.g Flex isn't supported yet in many old browser like IE8.

If you add compatibility info, frontend developers could add fallback (polyfill) for old browsers.

**Comment by shepmaster** [comment] 2016-07-09 18:52
Duplicate of #3

**Closed** 2016-07-09 22:14 UTC
