### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by martinheidegger** [NamPNQ/You-Dont-Need-Javascript#17] opened 2016-07-05 16:35 UTC
It would be awesome if this page had a browser-compatibility table that not just shows that these things work in css but also that they work cross/browser/platform.

**Comment by ZachSaucier** [comment] 2016-07-05 17:34
This is a duplicate of issue [#3](https://github.com/NamPNQ/You-Dont-Need-Javascript/issues/3)

**Closed** 2016-07-06 00:35 UTC
